"""add auth hardening tables

Revision ID: a1b2c3d4e5f6
Revises: dfd17d5dfbaa
Create Date: 2026-08-08 12:00:00.000000

Adds: users.email_verified / email_verified_at,
password_resets, email_verifications, audit_events.
(Sprint 07, Tracks B2 + B4.)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'dfd17d5dfbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(),
                                     nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(),
                                     nullable=True))
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_to', sa.String(length=256), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('provider_id', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_created_at'), 'email_events',
                    ['created_at'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets',
                    ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets',
                    ['user_id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_token_hash'),
                    'email_verifications', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verifications_user_id'),
                    'email_verifications', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'],
                    unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events',
                    ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_email_verifications_user_id'),
                  table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_token_hash'),
                  table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_password_resets_user_id'),
                  table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token_hash'),
                  table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_email_events_created_at'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
