"""initial schema

Revision ID: c8feb1ef5a6f
Revises: 
Create Date: 2026-08-04 00:47:55.146628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8feb1ef5a6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_raw', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=128), nullable=True),
    sa.Column('subfield', sa.String(length=128), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('methods_required', sa.Text(), nullable=True),
    sa.Column('funding_status', sa.String(length=64), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('freshness', sa.String(length=32), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('matched_anchors', sa.Text(), nullable=True),
    sa.Column('matched_keywords', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('position_type', sa.String(length=32), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_raw', name='uq_source_raw')
    )
    op.create_index(op.f('ix_opportunities_country'), 'opportunities', ['country'], unique=False)
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_opportunities_url'), 'opportunities', ['url'], unique=False)
    op.create_table('supervisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('methods', sa.Text(), nullable=True),
    sa.Column('recent_papers', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisors_country'), 'supervisors', ['country'], unique=False)
    op.create_index(op.f('ix_supervisors_name'), 'supervisors', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('match_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_feedback_match_id'), 'match_feedback', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_feedback_user_id'), 'match_feedback', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('subfield', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('methods', sa.Text(), nullable=True),
    sa.Column('tools', sa.Text(), nullable=True),
    sa.Column('target_roles', sa.Text(), nullable=True),
    sa.Column('countries_preferred', sa.Text(), nullable=True),
    sa.Column('funding_requirement', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_profile_id'), 'applications', ['profile_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'opportunity_id', name='uq_bookmark_profile_opportunity')
    )
    op.create_index(op.f('ix_bookmarks_opportunity_id'), 'bookmarks', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_profile_id'), 'bookmarks', ['profile_id'], unique=False)
    op.create_table('digest_preferences',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('include_matches', sa.Integer(), nullable=False),
    sa.Column('include_supervisors', sa.Boolean(), nullable=False),
    sa.Column('quiet_days', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('topic_score', sa.Float(), nullable=True),
    sa.Column('method_score', sa.Float(), nullable=True),
    sa.Column('skill_score', sa.Float(), nullable=True),
    sa.Column('location_score', sa.Float(), nullable=True),
    sa.Column('funding_score', sa.Float(), nullable=True),
    sa.Column('competitiveness_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_profile_id'), 'matches', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_profile_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('digest_preferences')
    op.drop_index(op.f('ix_bookmarks_profile_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_opportunity_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_applications_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_match_feedback_user_id'), table_name='match_feedback')
    op.drop_index(op.f('ix_match_feedback_match_id'), table_name='match_feedback')
    op.drop_table('match_feedback')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supervisors_name'), table_name='supervisors')
    op.drop_index(op.f('ix_supervisors_country'), table_name='supervisors')
    op.drop_table('supervisors')
    op.drop_index(op.f('ix_opportunities_url'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_country'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
